next.config.js

__dirname 사용 시 `ReferenceError: path is not defined ERROR` 에러가 나타나 해당 문제를 해결하였습니다
[참고 문서](https://improvisation.tistory.com/entry/Node-path-dirname-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-ReferenceError-path-is-not-defined-ERROR)

[#6] require 속성 추가

---

src/app/layout.tsx

X
- 컴포넌트는 layout.tsx에 한번만 적용 시켜주면, 그 뒤로는 함수로 호출하는 형식입니다.
- 많이 사용하는 거 기준으로 가져왔습니다.
```
// 성공
toast.sucess('메시지 내용');
// 실패
toast.error('메시지 내용');
// 커스텀 아이콘
toast('메시지 내용', {icon: '👏'});
```
<a href="https://react-hot-toast.com/">참고 링크</a>

[#7] react-hot-toast 세팅

---

.husky/pre-commit
package-lock.json
package.json
src/app/layout.tsx

1.husky로 git hook이 제어되어 eslint와 prettierr 검사 됩니다.
2.lint-staged 를 활용해서 staged(커밋 할 파일들) 상태에 파일들중 ts,tsx확장자만 커밋 시점에 검사됩니다.
3.eslint 타입스크립트 plugin 추가했습니다. (없으면 lint 에러 발생합니다.) 
4. prettier 패키지가 따로 없고 설정파일만있어서 패키지 추가했습니다.
만약 husky동작 시 권한 문제 발생하면 별도 권한을 부여해줘야합니다.
```chmod +x .husky/pre-commit```
husky 실패 
husky 성공

[#2] husky & lint-Staged 셋팅

---

src/constants/motion.ts

framer-motion을 세팅하였습니다 
constants 폴더 아래에 상수로 관리했어요
아래와 같이 구성하였습니다. 필요한 경우 import 해서 사용해 주세요
```t
자식 컴포넌트에 딜레이를 0.1s씩 주는 staggerOne, 
0.5s씩 주는 staggerHalf,
FadeIn, FadeInUp, FadeInScale, FadeInLeft, FadeInRight
```
번들 사이즈를 줄이기 위해 import 시에는 아래와 같이 사용해 주세요
```tsx
import { m } from "framer-motion";
```
framer-motion 적용하는 곳에는 **"use client"** 를 작성해 주세요
후에 공통적으로 **자주** 사용되는 framer-motion이 있다면 아래와 같이 framer-motion 템플릿을 만들어서 적용해도 좋을 것 같아요 ㅎㅎ
```tsx
function Template({ children }: { children: ReactNode }) {
return (
<m.div initial={{}} animate={{}} transition={{}}>
{children}
</m.div>
);
}
```

[#4] framer-motion

---

.github/DISCUSSION_TEMPLATE/DailyMeeting.yml
.github/DISCUSSION_TEMPLATE/ErrorLog.yml
.github/DISCUSSION_TEMPLATE/Study.yml

총 4개의 Discussion을 만들었습니다!
1. `DailyMeeting` : 회의록 작성은 여기에 해주시면 됩니다!
2. `Error` : 개발하다가 맞딱드린 에러를 공유해주시고, 해결 방법을 같이 찾아봅시다 🔍
3. `Study` : 프런트엔드 팀원들과 공유하고 싶은 _**react**_ 관련 이야기들을 적어봅시다 📝
4. `Vote` : 다른 팀원들의 의견이 필요할 때 간단하게 투표하면 좋을 거 같아서 만들어봤습니다. 기존의 Poll과 동일한 기능입니다 💪
늦어서 죄송합니다 😅
더 필요하다고 생각되는 템플릿 있으시면 말씀해주세요!

[#24] discussion template 생성

---

.github/workflows/lighthouse.yml
.gitignore
.lighthouserc.js
lighthouserc.js
package-lock.json
package.json
scripts/lighthouse.js

github actions과 light house를 연동하여 **자동으로 성능을 측정**하고 **pr을 날릴 시 댓글에 Lighthouse 보고서** 생성를 생성하도록 설정하였습니다
lighthouse는 웹페이지의 성능을 자세하게 제공해주어 수치화된 지표를 통해서 저희 서비스의 성능을 잘 체크할 수 있을 것 같아요 ㅎㅎ!
위 사진은 FCP 측정 항목에 대한 컬러코드 기준 예시입니다
정해진 범위에 따라 컬러코드와 점수가 결정되고 이는 전체 성능점수에 영향을 미치게 돼요
점수가 낮다면 이미지 최적화, 번들 최적화 등등에 신경쓰고 머지해주세요!
[lighthouse-ci 공식 문서](https://github.com/GoogleChrome/lighthouse-ci)

[#22] Lighthouse CI

---

.eslintrc.json
.github/workflows/ci.yml

일단 deploy 관련해서는 만들지 않았어요!
* `node -v` : node version 확인
* `npm ci` : dependencies 다운
* `npm run build` : build 하기
너무 간단해서 이게 정말 끝인가? 싶군요..🤔

[#28] npm ci 설정

---

.lighthouserc.js
scripts/lighthouse.js

lighthouse report 내용이 공통된 것이 연속으로 나와 이를 수정하였습니다
report 속성 빠진 것들 모두 추가하였습니당
light house 검사를 5번으로 설정했었는데 시간이 오래 걸리고 이전 결과를 보니 그 정도로 필요는 없을 것 같아 기본 (3)으로 설정하였습니다
아래는 추가한 사항들에 대한 설명입니다
Accessibility - 접근성 확인, 폰트 사이즈 등을 측정
Best practices - Best practices를 따라 개발되었는지 확인
PWA (Progressive Web App) -  웹과 네이티브 앱의 기능 모두의 이점을 가지도록 만들어진 서비스인지 체크
SEO - 검색 엔진 수집 최적화 측정
First Contentful Paint - 초기 렌더링 시간
Speed Index - 콘텐츠가 시각적으로 표시되는 진행 속도
Largest Contentful Paint - 가장 큰 콘텐츠를 렌더링 하는 데 걸리는 시간
Time to Interactive - 사용자가 페이지와 완전히 상호작용할 수 있을 때까지 걸리는 시간
Total Blocking Time - 사용자 입력에 페이지가 응답하지 못하도록 차단된 총 시간
Cumulative Layout Shift - 사용자가 예상치 못한 레이아웃 이동을 경험하는 것에 대한 점수
[관련 자료](https://web.dev/explore/metrics?hl=ko)

[#43] lighthouse report 내용 수정

---

src/components/atoms/Button/BackButton/index.tsx

간단하게 모바일 환경에서 사용할 뒤로가기 기능을 개발해놓았습니다

[#25] 뒤로가기 기능

---

src/utils/DateFormat.ts
src/utils/WorkOutDays.ts

- Date 타입 종류가 정해진게 없어서 임시로 `year-mm-dd` 만들었습니다.
- 추후 정해지면 변경하도록 하겠습니다 👮🏻‍♂️
- `WorkOutDays(유저 시작 날짜)`
<br />
```
import WorkOutDays from '@/utils/WorkOutDays';
function Home() {
const myDate = new Date('2024-02-29');
const nDays = WorkOutDays(myDate);
return (
<main style={{ fontSize: '20px', textAlign: 'center', marginTop: '200px' }}>
{nDays}일째 운동중
</main>
);
}
export default Home;
```
<br />

[#49] n일째 운동중 유틸

---

src/components/atoms/ImgDownLoad/index.tsx
src/utils/ImgDownLoad.ts

- `이미지 URL / 파일 이름 / 버튼 내용`은 props로 받는 형태로 만들었습니다.
```
try {
// Axios를 사용하여 이미지 데이터를 가져옵니다
const res = await axios.get(imgUrl, { responseType: 'blob' });
// 가져온 데이터를 Blob으로 변환
const blob = res.data;
// Blob을 이미지를 나타내는 URL로 변환
const imageUrl = window.URL.createObjectURL(blob);
// 다운로드를 위한 가상의 <a> 태그를 생성
const a = document.createElement('a');
a.href = imageUrl;
a.download = fileName;
document.body.appendChild(a);
// 가상의 <a> 태그를 클릭합니다
a.click();
// 다운로드가 완료되면 생성한 URL을 해제합니다
window.URL.revokeObjectURL(imageUrl);
} catch (error) {
toast.error('이미지 다운로드 오류');
}
};
```
- 이미지 다운로드를 하기 위해서 url로 이미지를 넣어줬는데, 현재 localhost의 주소와 이미지 url 주소가 달라
- `CORS`오류가 발생하고 있습니다.
- 그래서 일단 `크롬 보안을 없애는 형태`로 테스트를 진행 하였고, 정상적으로 다운로드 되는 것을 확인 했습니다.
<br />

[#60] 이미지 다운로드 컴포넌트

---

src/components/atoms/Name/Name.module.scss
src/components/atoms/Name/index.tsx
src/components/atoms/PostContent/index.tsx
src/components/molecules/Comment/index.tsx
src/components/molecules/PostProfile/index.tsx
src/styles/fontWeights.scss
src/styles/fonts.scss

만들어진 코드들을 기반으로 간편하게 쓸 수 있는 fonts theme을 만들었습니다!
scss에서 fonts.scss를 import 해주기만 한다면, 별도의 코드 없이 사용 가능해요~
```tsx
interface Name {
name: string;
size: 'size' | 'medium' | 'large';
}
function Name({ name, size }: Name) {
return <p className={cn('name', size)}>{name}</p>;
}
```
이런 구조에서,
```scss
@import '@/styles/fonts.scss';
```
이렇게만 해주시면 됩니다!

[#107]  fonts theme

---

src/components/Layout/Layout.module.scss
src/components/organisms/Footer/Footer.module.scss
src/styles/colors.scss
src/styles/globalStyle.scss

global color theme을 정의하였습니다
최대한 알아보기 쉽게 정리했어용 (정리의 신이라 불러주세요)
white는 쓰는 데가 없어서 저희 디자인 white 색상으로 변경했어요
기본 색상이랑 배경 색상도 지정했어용
전에 윤혁님이 알려주신 플러그인인데 추천드려용 !!

[#111] color theme

---

src/components/atoms/LabelInput/LabelInput.module.scss
src/components/atoms/LabelInput/index.tsx
src/hooks/useLabelInput.ts
src/styles/globalStyle.scss

- 일단 기본적인 기능만 되도록 설정했습니다
- 스타일에 관해서는 디자인 나오는대로 수정하도록 하겠습니다
<br />
- `Enter`를 누르면 라벨이 추가되도록 설정했습니다
- 빨간 버튼을 누르면 `삭제` 되도록 설정했습니다 ❌
- 같은 값은 입력하게 되면 `input 값을 지우고, 라벨에 추가되지 않도록` 설정했습니다
- 코드 보시면 라벨이 추가되면 id 값을 1씩 추가해서 설정 했는데 더 좋은 방법이 있을까 의견을 나눠보고 싶습니다 👀
- input 기본 스타일 없앴습니다 👀
<br />

[#76] 라벨 입력 컴포넌트

---

next.config.js
src/styles/globalStyle.scss

[#128] 폰트 적용

---

src/app/layout.tsx

naver search advisor를 적용하였습니당
naver 계정은 노션에 작성해놓았습니다!
viewport 설정도 추가하였습니다

[#99] naver search advisor 

---

.github/workflows/image.yml

**이미지 압축 및 최적화 관련 ci**를 부착하였습니다
pr시 자동으로 이미지를 압축하여 **용량과 성능을 개선**할 수 있습니당
무손실 압축이라 빠르고 효율적인 이미지 최적화에 적합하여 넣게 되었습니다!
아래와 같이 확인하실 수 있습니다!

[#104] compress images ci

---

src/app/setting/page.tsx
src/app/setting/resign/page.tsx
src/components/atoms/Button/ReSignButton/ReSignButton.module.scss
src/components/atoms/Button/ReSignButton/index.tsx
src/components/atoms/Button/ToggleButton/ToggleButton.module.scss
src/components/atoms/Button/ToggleButton/index.tsx
src/components/molecules/ResignNickName/ResignNickName.module.scss
src/components/molecules/ResignNickName/index.tsx
src/components/molecules/ResignText/ResignText.module.scss
src/components/molecules/ResignText/index.tsx
src/components/molecules/ResignTwinButton/ResignTwinButton.module.scss
src/components/molecules/ResignTwinButton/index.tsx
src/components/molecules/SettingArticle/SettingArticle.module.scss
src/components/molecules/SettingArticle/index.tsx
src/components/organisms/ResignSection/ResignSection.module.scss
src/components/organisms/ResignSection/index.tsx
src/components/organisms/SettingSection/SettingSection.module.scss
src/components/organisms/SettingSection/index.tsx
src/hooks/useCheckNickName.ts
src/hooks/useResignButton.ts
src/styles/colors.scss

- 토글 버튼 새로 디자인 했습니다..!
- input 값에 닉네임과 일치하는 값이 들어오면 활성화 되도록 설정했습니다. (추후 API 값 넣어지면 수정만 하면 됩니다.)
- 일단 수영님꺼 버튼과 비슷한 디자인 있지만 아직 pr이 머지 되지 않아서 따로 만들었습니다.
- 페이지 이동하는 부분들은 아직 만들어진 페이지가 없어서 임시로 넣어뒀습니다 (추후 수정)
- 이번에도 컴포넌트명 괜찮은지 봐주시면 감사하겠습니다 👮🏻‍♂️
https://github.com/GymHubCommunity/GymHub-FE/assets/49686619/d61b92a3-29ed-448e-9f03-d814dbddbcf1

[#136] 설정 페이지 디자인

---

.eslintrc.json
.github/workflows/ci.yml

[#146] npm ci 파일 복구~

---

src/app/api/auth/callback/[...provider]/page.tsx

가입했는 지 여부를 확인하고 그에 따른 router를 설정하였슴니다 ㅎㅎ😼

[#204] 회원가입을 했을 경우 로직

---

src/components/molecules/ExerciseRoutine/ExerciseRoutine.module.scss
src/components/molecules/ExerciseRoutine/index.tsx
src/types/records.ts
src/utils/DateFormat.ts

[#237] 달에 해당하는 운동기록 조회

---

next.config.js
src/apis/Query/Follow/index.tsx
src/apis/Query/Post/useGetPost.ts
src/apis/Query/Post/useGetPostwithScroll.ts
src/apis/post.ts
src/apis/user/useGetInfo.ts
src/app/follow/[userId]/page.tsx
src/app/mypage/page.tsx
src/app/post/[postId]/page.tsx
src/components/atoms/Button/FollowToggleButton/FollowToggleButton.module.scss
src/components/atoms/Button/FollowToggleButton/index.tsx
src/components/atoms/CountInfo/index.tsx
src/components/molecules/Profile/index.tsx
src/components/organisms/FollowSection/FollowSection.module.scss
src/components/organisms/FollowSection/index.tsx
src/components/organisms/Header/BackButtonHeader/index.tsx
src/components/organisms/PostSection/MypagePostSection.tsx
src/components/organisms/PostSection/index.tsx
src/hooks/useCheckNickName.ts
src/hooks/useMainSection.ts
src/hooks/usePostSection.ts
src/middleware.ts
src/types/GetPost.ts

마이페이지 작업 완료하였습니다
운동 일수는 현재 게시글 개수와 동일하게 설정하였습니다

[#234] 마이페이지

---

src/app/snapshot/page.tsx
src/components/atoms/Button/FloatingButton/index.tsx
src/components/atoms/Button/ToggleMenu/ToggleItems/index.tsx
src/components/atoms/Button/ToggleMenu/index.tsx
src/components/molecules/DailyRecord/index.tsx
src/components/molecules/ExerciseRoutine/Snapshot/Snapshot.module.scss
src/components/molecules/ExerciseRoutine/Snapshot/index.tsx
src/components/molecules/PostArticle/index.tsx
src/components/molecules/PostProfile/index.tsx
src/components/molecules/RoutineArticle/index.tsx
src/components/molecules/UserRoutineArticle/index.tsx
src/components/organisms/MainSection/index.tsx
src/components/organisms/Modal/index.tsx
src/components/organisms/PostSection/MypagePostSection.tsx
src/components/organisms/PostSection/PostSection.module.scss
src/components/organisms/PostSection/index.tsx
src/components/organisms/Records/index.tsx
src/components/organisms/SearchSection/index.tsx
src/constants/ToggleMenu.ts
src/hooks/useToggleItems.ts
src/hooks/useToggleMenu.ts
src/middleware.ts
src/types/toggle.ts

스냅샷 기능을 개발하였습니다
스냅샷 기능들은 스웨거에서 동작 확인이 가능하지만 화면에 그리는 데에 있어서 수정이 필요합니다
(스냅샷 저장 기능은 가능합니다)
스냅샷이 불러와지나 디자인 및 구성을 변경해야될 것 같습니다
삭제가 원래 가능하였는데 모달 추가 후 작동하지 않아 수정이 필요합니다
스냅샷에 관련한 추가 개발 내용은 노션에 정리해두었습니다
모달이나 토글 등 변경된 사항이 많아 후에 리팩토링 진행하겠습니다

[#243] 운동기록 스냅샷 기능

---

src/components/organisms/AddPost/index.tsx
src/components/organisms/ImageSection/ImageSection.module.scss
src/components/organisms/ImageSection/index.tsx

- Image 영역 컴포넌트를 별도로 분리하였습니다. 
- 비즈니스 로직도 훅으로 분리해볼까하는데 생각보다 복잡하네요 작업 예정입니다

[#254] AddPost 컴포넌트 리펙토링 

---

.github/CODEOWNERS
src/apis/Query/Records/useGetRecords.ts
src/app/records/select/page.tsx
src/components/atoms/Input/DateInput/index.tsx
src/components/atoms/UserRoutine/index.tsx
src/components/molecules/DailyRecord/index.tsx
src/components/molecules/EditRecord/EditRecordsSection/index.tsx
src/components/molecules/ExerciseRoutine/index.tsx
src/components/molecules/RecordsHeader/RecordsHeader.module.scss
src/components/molecules/RecordsHeader/index.tsx
src/components/molecules/UserRoutineArticle/index.tsx
src/components/organisms/Common.module.scss
src/components/organisms/Header/BackButtonHeader/index.tsx
src/components/organisms/Modal/index.tsx
src/components/organisms/Records/Records.module.scss
src/components/organisms/Records/index.tsx
src/components/organisms/SelectSection/page.tsx
src/hooks/useDateHeaderControls.ts
src/hooks/useRecords.ts

X
- 현재 다음 달로 넘어 갔을 때, 날짜를 한번 클릭해야 데이터가 `fetch` 됩니다.
- 해당 부분은 추후 수정하도록 하겠습니다.
- 기능에 해당하는 부분은 `커스텀 훅`으로 분리했습니다.
- 기타 오류가 있던 스타일들을 수정했습니다.

[#265] 운동 기록 조회 일자 기준으로만 조회 되는 현상

---

src/apis/Query/Post/useGetPostwithScroll.ts
src/components/atoms/Button/StoryButton/index.tsx
src/components/atoms/Story/index.tsx
src/components/molecules/BlankStory/BlankStory.module.scss
src/components/molecules/StoryArticle/index.tsx
src/components/organisms/MainSection/index.tsx

- 스토리 기능을 구현하였습니다 
- 스토리 누르면 프로필로 이동 가능합니다 👍🏻
https://github.com/GymHubCommunity/GymHub-FE/assets/49686619/de2a1eb3-8642-47b1-a227-0b1bea492f19

[#270] 스토리 기능 구현
